// Code generated by go-swagger; DO NOT EDIT.

package astrobin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UploadImageHandlerFunc turns a function with the right signature into a upload image handler
type UploadImageHandlerFunc func(UploadImageParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UploadImageHandlerFunc) Handle(params UploadImageParams) middleware.Responder {
	return fn(params)
}

// UploadImageHandler interface for that can handle valid upload image params
type UploadImageHandler interface {
	Handle(UploadImageParams) middleware.Responder
}

// NewUploadImage creates a new http.Handler for the upload image operation
func NewUploadImage(ctx *middleware.Context, handler UploadImageHandler) *UploadImage {
	return &UploadImage{Context: ctx, Handler: handler}
}

/*
	UploadImage swagger:route POST /upload astrobin uploadImage

Upload images to providers
*/
type UploadImage struct {
	Context *middleware.Context
	Handler UploadImageHandler
}

func (o *UploadImage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUploadImageParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
