// Code generated by go-swagger; DO NOT EDIT.

package astrobin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/NFortun/Astrobot/models"
)

// UploadImageNoContentCode is the HTTP code returned for type UploadImageNoContent
const UploadImageNoContentCode int = 204

/*
UploadImageNoContent Success

swagger:response uploadImageNoContent
*/
type UploadImageNoContent struct {
}

// NewUploadImageNoContent creates UploadImageNoContent with default headers values
func NewUploadImageNoContent() *UploadImageNoContent {

	return &UploadImageNoContent{}
}

// WriteResponse to the client
func (o *UploadImageNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*
UploadImageDefault default error message

swagger:response uploadImageDefault
*/
type UploadImageDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUploadImageDefault creates UploadImageDefault with default headers values
func NewUploadImageDefault(code int) *UploadImageDefault {
	if code <= 0 {
		code = 500
	}

	return &UploadImageDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the upload image default response
func (o *UploadImageDefault) WithStatusCode(code int) *UploadImageDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the upload image default response
func (o *UploadImageDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the upload image default response
func (o *UploadImageDefault) WithPayload(payload *models.Error) *UploadImageDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the upload image default response
func (o *UploadImageDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UploadImageDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
