// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"astrobot/models"
)

// GetImageOfTheDayOKCode is the HTTP code returned for type GetImageOfTheDayOK
const GetImageOfTheDayOKCode int = 200

/*
GetImageOfTheDayOK Success

swagger:response getImageOfTheDayOK
*/
type GetImageOfTheDayOK struct {

	/*
	  In: Body
	*/
	Payload *models.ImageResponse `json:"body,omitempty"`
}

// NewGetImageOfTheDayOK creates GetImageOfTheDayOK with default headers values
func NewGetImageOfTheDayOK() *GetImageOfTheDayOK {

	return &GetImageOfTheDayOK{}
}

// WithPayload adds the payload to the get image of the day o k response
func (o *GetImageOfTheDayOK) WithPayload(payload *models.ImageResponse) *GetImageOfTheDayOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get image of the day o k response
func (o *GetImageOfTheDayOK) SetPayload(payload *models.ImageResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetImageOfTheDayOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetImageOfTheDayDefault default error message

swagger:response getImageOfTheDayDefault
*/
type GetImageOfTheDayDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetImageOfTheDayDefault creates GetImageOfTheDayDefault with default headers values
func NewGetImageOfTheDayDefault(code int) *GetImageOfTheDayDefault {
	if code <= 0 {
		code = 500
	}

	return &GetImageOfTheDayDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get image of the day default response
func (o *GetImageOfTheDayDefault) WithStatusCode(code int) *GetImageOfTheDayDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get image of the day default response
func (o *GetImageOfTheDayDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get image of the day default response
func (o *GetImageOfTheDayDefault) WithPayload(payload *models.Error) *GetImageOfTheDayDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get image of the day default response
func (o *GetImageOfTheDayDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetImageOfTheDayDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
