// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetImageOfTheDayHandlerFunc turns a function with the right signature into a get image of the day handler
type GetImageOfTheDayHandlerFunc func(GetImageOfTheDayParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetImageOfTheDayHandlerFunc) Handle(params GetImageOfTheDayParams) middleware.Responder {
	return fn(params)
}

// GetImageOfTheDayHandler interface for that can handle valid get image of the day params
type GetImageOfTheDayHandler interface {
	Handle(GetImageOfTheDayParams) middleware.Responder
}

// NewGetImageOfTheDay creates a new http.Handler for the get image of the day operation
func NewGetImageOfTheDay(ctx *middleware.Context, handler GetImageOfTheDayHandler) *GetImageOfTheDay {
	return &GetImageOfTheDay{Context: ctx, Handler: handler}
}

/*
	GetImageOfTheDay swagger:route GET /imageoftheday getImageOfTheDay

Get the astrobin image of the day
*/
type GetImageOfTheDay struct {
	Context *middleware.Context
	Handler GetImageOfTheDayHandler
}

func (o *GetImageOfTheDay) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetImageOfTheDayParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
