// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"mime/multipart"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// UploadImageMaxParseMemory sets the maximum size in bytes for
// the multipart form parser for this operation.
//
// The default value is 32 MB.
// The multipart parser stores up to this + 10MB.
var UploadImageMaxParseMemory int64 = 32 << 20

// NewUploadImageParams creates a new UploadImageParams object
//
// There are no default values defined in the spec.
func NewUploadImageParams() UploadImageParams {

	return UploadImageParams{}
}

// UploadImageParams contains all the bound params for the upload image operation
// typically these are obtained from a http.Request
//
// swagger:parameters UploadImage
type UploadImageParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: formData
	*/
	Caption *string
	/*name of the file
	  Required: true
	  In: formData
	*/
	Name string
	/*file to upload
	  Required: true
	  In: formData
	*/
	UpFile io.ReadCloser
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUploadImageParams() beforehand.
func (o *UploadImageParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := r.ParseMultipartForm(UploadImageMaxParseMemory); err != nil {
		if err != http.ErrNotMultipart {
			return errors.New(400, "%v", err)
		} else if err := r.ParseForm(); err != nil {
			return errors.New(400, "%v", err)
		}
	}
	fds := runtime.Values(r.Form)

	fdCaption, fdhkCaption, _ := fds.GetOK("caption")
	if err := o.bindCaption(fdCaption, fdhkCaption, route.Formats); err != nil {
		res = append(res, err)
	}

	fdName, fdhkName, _ := fds.GetOK("name")
	if err := o.bindName(fdName, fdhkName, route.Formats); err != nil {
		res = append(res, err)
	}

	upFile, upFileHeader, err := r.FormFile("upFile")
	if err != nil {
		res = append(res, errors.New(400, "reading file %q failed: %v", "upFile", err))
	} else if err := o.bindUpFile(upFile, upFileHeader); err != nil {
		// Required: true
		res = append(res, err)
	} else {
		o.UpFile = &runtime.File{Data: upFile, Header: upFileHeader}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCaption binds and validates parameter Caption from formData.
func (o *UploadImageParams) bindCaption(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Caption = &raw

	return nil
}

// bindName binds and validates parameter Name from formData.
func (o *UploadImageParams) bindName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("name", "formData", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("name", "formData", raw); err != nil {
		return err
	}
	o.Name = raw

	return nil
}

// bindUpFile binds file parameter UpFile.
//
// The only supported validations on files are MinLength and MaxLength
func (o *UploadImageParams) bindUpFile(file multipart.File, header *multipart.FileHeader) error {
	return nil
}
